// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json.Serialization;
using AzureMcp.Sql.Commands;

namespace AzureMcp.Sql.Services.Models
{
    /// <summary>
    /// A class representing the SqlServerAadAdministrator data model.
    /// Azure Active Directory administrator.
    /// </summary>
    public partial class SqlServerAadAdministratorData
    {
        /// <summary> The resource ID for the resource. </summary>
        [JsonPropertyName("id")]
        public string ResourceId { get; set; }
        /// <summary> The type of the resource. </summary>
        [JsonPropertyName("type")]
        public string ResourceType { get; set; }
        /// <summary> The name of the resource. </summary>
        [JsonPropertyName("name")]
        public string ResourceName { get; set; }
        /// <summary> Properties of the Azure Active Directory administrator. </summary>
        [JsonPropertyName("properties")]
        public SqlServerAadAdministratorProperties Properties { get; set; }

        // Read the JSON response content and create a model instance from it.
        public static SqlServerAadAdministratorData FromJson(JsonElement source)
        {
            return JsonSerializer.Deserialize<SqlServerAadAdministratorData>(source, SqlJsonContext.Default.SqlServerAadAdministratorData);
        }
    }
}
